<?php

add_action( 'acf/include_fields', function() {
	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}

	acf_add_local_field_group( array(
	'key' => 'group_66a5fca089710',
	'title' => 'Page Options',
	'fields' => array(
		array(
			'key' => 'field_66a5fca101447',
			'label' => 'NASA Official',
			'name' => 'nasa_official',
			'aria-label' => '',
			'type' => 'user',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'role' => '',
			'return_format' => 'array',
			'multiple' => 0,
			'allow_null' => 0,
			'bidirectional' => 0,
			'bidirectional_target' => array(
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );

	acf_add_local_field_group( array(
	'key' => 'group_66a5fd2924f59',
	'title' => 'Navigation Options',
	'fields' => array(
		array(
			'key' => 'field_66a5fd2958a40',
			'label' => 'Remove Left Navigation',
			'name' => 'otp_hide',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_66a5fd6858a41',
			'label' => 'Type',
			'name' => 'navigation_type',
			'aria-label' => '',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_66a5fd2958a40',
						'operator' => '!=',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'single_page' => 'Single Page',
				'multiple_page' => 'Multiple Page',
			),
			'default_value' => 'single_page',
			'return_format' => 'value',
			'allow_null' => 0,
			'other_choice' => 0,
			'layout' => 'horizontal',
			'save_other_choice' => 0,
		),
		array(
			'key' => 'field_66a5fe3658a42',
			'label' => 'Heading tags to use',
			'name' => 'otp_heading_tags',
			'aria-label' => '',
			'type' => 'radio',
			'instructions' => 'Select which tags get used to generate the navigation.',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_66a5fd2958a40',
						'operator' => '!=',
						'value' => '1',
					),
					array(
						'field' => 'field_66a5fd6858a41',
						'operator' => '==',
						'value' => 'single_page',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'h2 h3 h4' => 'h2, h3, and h4',
				'h2 h3' => 'h2 and h3',
				'h2' => 'h2',
			),
			'default_value' => 'h2 h3 h4',
			'return_format' => 'value',
			'allow_null' => 0,
			'other_choice' => 0,
			'layout' => 'horizontal',
			'save_other_choice' => 0,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
		),
	),
	'menu_order' => 1,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );

	acf_add_local_field_group( array(
	'key' => 'group_66a5fae9847fc',
	'title' => 'Landing Page Settings',
	'fields' => array(
		array(
			'key' => 'field_66a5fae97e0a4',
			'label' => 'Hero Callout',
			'name' => 'lpt_hero_callout',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => 'Hero callout:',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66a5fb6b7e0a7',
			'label' => 'Leading paragraph',
			'name' => 'lpt_leading_paragraph',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => 'Bring attention to a project priority',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66a5fb9b7e0a8',
			'label' => 'Sub paragraph',
			'name' => 'lpt_sub_paragraph',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'rows' => '',
			'placeholder' => 'Support the callout with some short explanatory text. You don’t need more than a couple of sentences.',
			'new_lines' => 'br',
		),
		array(
			'key' => 'field_66a6019fc20b3',
			'label' => 'Show Hero Button',
			'name' => 'lpt_show_button',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_66a601cbc20b4',
			'label' => 'Button Text',
			'name' => 'lpt_button_text',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_66a6019fc20b3',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => 'Call to action',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66a6023dcb123',
			'label' => 'Button URL',
			'name' => 'lpt_button_url',
			'aria-label' => '',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_66a6019fc20b3',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'https://example.com/',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'template-landing.blade.php',
			),
		),
	),
	'menu_order' => 4,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );
} );